name: docs_quantum_rfs
channels:

  # - conda-forge

  # - defaults
dependencies:
    # Base depends
  - python
  - pip
  
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton

  -numpy




    # Pip-only installs
  - pip:
    - -e ../
    - sphinx-autoapi
    - sphinx-rtd-theme
